### Histograms of observation counts per profile

```{r, t_summary_obs_count1_setup, echo = FALSE, message = FALSE, warning = FALSE}

summary_table_netcdf_count1 <- summary_table_netcdf %>%
  filter(obs_count <= {{count1_1}})
summary_table_netcdf_count2 <- summary_table_netcdf %>%
  filter(obs_count <= {{count1_2}})
summary_table_netcdf_count3 <- summary_table_netcdf %>%
  filter(obs_count >= {{count1_3}})

```

::: {.panel-tabset}

#### All values

```{r, t_summary_obs_count1_all, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 6}
p_obs_count_hist <- create_obs_count_hist(summary_table_netcdf, "All values")

print(p_obs_count_hist)

```

#### ≤{{count1_1}}

```{r, t_summary_obs_count1_count1, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 6}
p_obs_count_hist_count1 <- create_obs_count_hist(summary_table_netcdf_count1, "Filtered by ≤{{count1_1}}")

print(p_obs_count_hist_count1)

```

#### ≤{{count1_2}}

```{r, t_summary_obs_count1_count2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 6}
p_obs_count_hist_count2 <- create_obs_count_hist(summary_table_netcdf_count2, "Filtered by ≤{{count1_2}}")

print(p_obs_count_hist_count2)

```

#### ≥{{count1_3}}

```{r, t_summary_obs_count1_count3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 6}
p_obs_count_hist_count3 <- create_obs_count_hist(summary_table_netcdf_count3, "Filtered by ≥{{count1_3}}")

print(p_obs_count_hist_count3)

```

:::

### Mapped locations of {{count2_1}}-{{count2_2}}, {{count3_1}}-{{count3_2}}, {{count4_1}}-{{count4_2}}, and ≥{{count5}} observations

::: {.panel-tabset}

#### {{count2_1}}-{{count2_2}}

```{r, t_summary_obs_count2_obs1, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}
p_long_x_lat_obs1 <- summary_table_netcdf %>%
  filter(obs_count >= {{count2_1}} & obs_count <= {{count2_2}}) %>%
  mutate(longitude = {{longitude_var_name}}, latitude = {{latitude_var_name}}) %>%
  create_region_scatter("#Obs: {{count2_1}}-{{count2_2}}", lat_range, lon_range)

print(p_long_x_lat_obs1)

```

#### {{count3_1}}-{{count3_2}}

```{r, t_summary_obs_count2_obs2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}
p_long_x_lat_obs2 <- summary_table_netcdf %>%
  filter(obs_count >= {{count3_1}} & obs_count <= {{count3_2}}) %>%
  mutate(longitude = {{longitude_var_name}}, latitude = {{latitude_var_name}}) %>%
  create_region_scatter("#Obs: {{count3_1}}-{{count3_2}}", lat_range, lon_range)

print(p_long_x_lat_obs2)

```

#### {{count4_1}}-{{count4_2}}

```{r, t_summary_obs_count2_obs3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}
p_long_x_lat_obs3 <- summary_table_netcdf %>%
  filter(obs_count >= {{count4_1}} & obs_count <= {{count4_2}}) %>%
  mutate(longitude = {{longitude_var_name}}, latitude = {{latitude_var_name}}) %>%
  create_region_scatter("#Obs: {{count4_1}}-{{count4_2}}", lat_range, lon_range)

print(p_long_x_lat_obs3)

```

#### ≥{{count5}}

```{r, t_summary_obs_count2_obs4, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}
p_long_x_lat_obs4 <- summary_table_netcdf %>% filter(obs_count >= {{count5}}) %>%
  mutate(longitude = {{longitude_var_name}}, latitude = {{latitude_var_name}}) %>%
  create_region_scatter("#Obs: ≥{{count5}}", lat_range, lon_range)

print(p_long_x_lat_obs4)

```

:::
