### Number of profiles

```{r, t_summary_dist1, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}

df_year <- summary_table_netcdf %>%
  mutate(x = format(profile_timestamp, "%Y"))

df_month <- summary_table_netcdf %>%
  mutate(x = format(profile_timestamp, "%m"))

```

::: {.panel-tabset}
#### Year

```{r, t_summary_dist2, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_year_hist <- create_sample_time_hist(df_year, "Year")

print(p_year_hist)

```

#### Month

```{r, t_summary_dist3, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_month_hist <- create_sample_time_hist(df_month, "Month")

print(p_month_hist)

```
:::

### Mapped locations of four time spans

 - **{{time_span1}}**: `r paste0("from ", {{time_span1_from}}, " to ", {{time_span1_to}})`
 - **{{time_span2}}**: `r paste0("from ", {{time_span2_from}}, " to ", {{time_span2_to}})`
 - **{{time_span3}}**: `r paste0("from ", {{time_span3_from}}, " to ", {{time_span3_to}})`
 - **{{time_span4}}**: `r paste0("from ", {{time_span4_from}}, " to ", {{time_span4_to}})`

```{r, t_summary_dist4, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = {{plot_height}}}

ts_lst <- split_time_spans(summary_table_netcdf)

p_long_x_lat_ts1 <- get_loc_by_timespan(ts_lst, "{{time_span1}}") %>%
  create_region_scatter("Time span: {{time_span1}}", lat_range, lon_range)

p_long_x_lat_ts2 <- get_loc_by_timespan(ts_lst, "{{time_span2}}") %>%
  create_region_scatter("Time span: {{time_span2}}", lat_range, lon_range)

p_long_x_lat_ts3 <- get_loc_by_timespan(ts_lst, "{{time_span3}}") %>%
  create_region_scatter("Time span: {{time_span3}}", lat_range, lon_range)

p_long_x_lat_ts4 <- get_loc_by_timespan(ts_lst, "{{time_span4}}") %>%
  create_region_scatter("Time span: {{time_span4}}", lat_range, lon_range)

print(plot_grid(p_long_x_lat_ts1, p_long_x_lat_ts2,
                p_long_x_lat_ts3, p_long_x_lat_ts4, nrow = {{plot_nrow}}))

```